#!/usr/bin/env python3

import argparse
import hashlib
from pathlib import Path

APP_NAME = "ClipACanvas"
DIST_DIR = Path("dist")
WEBSITE_URL = "https://clipacanvas.vercel.app"
REPO_URL = "https://github.com/mechreaper007x/ClipACanvas"

EXPECTED_FILES = [
    "ClipACanvas-Setup.exe",
    "ClipACanvas-windows.zip",
    "ClipACanvas-macos.zip",
]


def calculate_sha256(filepath: Path) -> str:
    sha256_hash = hashlib.sha256()
    with open(filepath, "rb") as f:
        for byte_block in iter(lambda: f.read(4096), b""):
            sha256_hash.update(byte_block)
    return sha256_hash.hexdigest()


def generate_checksums() -> None:
    print(f"Generating SHA256 checksums for {APP_NAME}...")
    output_file = DIST_DIR / "SHA256SUMS.txt"

    lines = []
    for filename in EXPECTED_FILES:
        filepath = DIST_DIR / filename
        if filepath.exists():
            checksum = calculate_sha256(filepath)
            lines.append(f"{checksum}  {filename}")
            print(f"  {filename}: {checksum[:12]}...")
        else:
            print(f"  SKIP: {filename} (not found in dist/)")

    if lines:
        output_file.write_text("\n".join(lines) + "\n", encoding="utf-8")
        print(f"Checksums saved to {output_file}")
    else:
        print("No artifacts found. Nothing to generate.")


def generate_release_notes(version: str) -> None:
    print(f"Generating RELEASE_NOTES.md for {version}...")
    output_file = DIST_DIR / "RELEASE_NOTES.md"

    content = f"""# Clip.A.Canvas {version}

**Clip.A.Canvas** turns HTML/CSS/JS animations into MP4 videos locally.

### Key Features
- High-performance Chromium rendering.
- Local FFmpeg encoding (no cloud privacy leaks).
- AI-friendly workflow (paste code, get video).

### Installation
1. Download the installer (`ClipACanvas-Setup.exe`) or the portable ZIP.
2. Run the application.
3. Paste your animation code and hit **Convert**.

### Links
- Website: {WEBSITE_URL}
- GitHub: {REPO_URL}

---
Generated by build_release_assets.py
"""
    output_file.write_text(content, encoding="utf-8")
    print(f"Release notes saved to {output_file}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Prepare release assets for Clip.A.Canvas")
    parser.add_argument("--version", default="v1.0.0", help="Release version (e.g., v1.0.0)")
    args = parser.parse_args()

    if not DIST_DIR.exists():
        print("ERROR: dist/ folder does not exist. Run build_desktop.py first.")
        return

    generate_checksums()
    generate_release_notes(args.version)


if __name__ == "__main__":
    main()
